### ISSUE TITLE
Use mapping lib

### ISSUE THREAD

**Issue by THenry14** [software-mansion/cairo-profiler#110]
https://github.com/software-mansion/cairo-annotations/issues/4

**Comment by THenry14** [comment]
https://github.com/software-mansion/cairo-annotations/pull/15

**Comment by ksew1** [comment]
I believe we can take the following actions:

- Utilize trace-data from `cairo-annotations`. We should deprecate trace-data in the profiler and include a message indicating that it will be removed in the next version.
-Use `map_pcs_to_sierra_statement_ids` in some parts of the code here: [function_trace_builder.rs#L49](https://github.com/software-mansion/cairo-profiler/blob/4466cb036ca4eea10d7970e0e99727e6cdeb80f7/crates/cairo-profiler/src/trace_reader/function_trace_builder.rs#L49).
- Replace the existing implementation with `cairo-annotations`'s `ProfilerAnnotations` instead of using the current approach in [sierra_loader.rs#L45](https://github.com/software-mansion/cairo-profiler/blob/4466cb036ca4eea10d7970e0e99727e6cdeb80f7/crates/cairo-profiler/src/sierra_loader.rs#L45C1-L45C77).
